In [60]:
import pandas as pd

df = pd.read_csv("googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [61]:
#PART1

In [62]:
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [63]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

In [64]:
df.shape

(10841, 13)

In [65]:
df.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
categorical_columns = df.select_dtypes(include=["object", "string"]).columns
numerical_columns = df.select_dtypes(include=["number"]).columns

categorical_columns, numerical_columns

(Index(['App', 'Category', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
        'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
        'Android Ver'],
       dtype='str'),
 Index(['Rating'], dtype='str'))

In [67]:
#6) Rating, Size, Installs
#7) Corrupted row shifting column values, Invalid rating values, Data types in numerical columns
#8) Ver curr and android

In [68]:
#part2

In [91]:
df.isnull().sum()

app                  0
category             0
rating            1463
reviews              0
installs             0
type                 1
price                0
content_rating       0
genres               0
last_updated         0
current_ver          8
android_ver          2
size_mb           1227
dtype: int64

In [70]:
df.duplicated().sum()

np.int64(483)

In [71]:
df[df["Rating"] > 5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [72]:
df["Reviews"].describe()

count     10841
unique     6002
top           0
freq        596
Name: Reviews, dtype: object

In [73]:
df["Category"].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [74]:
#part3

In [75]:
missing_percent = df.isnull().mean() * 100
missing_percent[missing_percent > 0].sort_values(ascending=False)

Rating            13.596532
Current Ver        0.073794
Android Ver        0.027673
Content Rating     0.009224
Type               0.009224
dtype: float64

In [76]:
"""
#Rating (~14%) - Fill with median
#Current Ver (~8%) - Leave as missing or consider dropping later
#Android Ver (~3%) - Fill with mode
#Content Rating(<1%) - Fill with mode
#Type (<1%) - Fill with mode
"""

'\n#Rating (~14%) - Fill with median\n#Current Ver (~8%) - Leave as missing or consider dropping later\n#Android Ver (~3%) - Fill with mode\n#Content Rating(<1%) - Fill with mode\n#Type (<1%) - Fill with mode\n'

In [77]:
#part4

In [92]:
df = df[df["Category"] != "1.9"]

KeyError: 'Category'

In [79]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [80]:
df["reviews"] = df["reviews"].astype(int)

In [81]:
df["installs"] = (
    df["installs"]
      .str.replace(",", "")
      .str.replace("+", "")
      .astype(int)
)

In [82]:
df["price"] = (
    df["price"]
      .str.replace("$", "", regex=False)
      .astype(float)
)

In [83]:
def size_to_mb(size):
    if size.endswith("M"):
        return float(size.replace("M", ""))
    elif size.endswith("k"):
        return float(size.replace("k", "")) / 1024
    else:
        return None

df["size_mb"] = df["size"].apply(
    lambda x: size_to_mb(x) if isinstance(x, str) else None
)

In [84]:
df = df.drop_duplicates(subset="app")

In [85]:
df = df.drop(columns=["size"])

In [86]:
#part5 is_paid log_reviews 
- installs_per_rating – combined popularity and quality metric

SyntaxError: invalid character '–' (U+2013) (2849293991.py, line 2)

In [ ]:
df["is_paid"] = df["price"] > 0

In [ ]:
import numpy as np

df["log_reviews"] = np.log1p(df["reviews"])

In [ ]:
df["installs_per_rating"] = df["installs"] / df["rating"]

In [90]:
df[[
    "price", "is_paid",
    "reviews", "log_reviews",
    "installs", "rating", "installs_per_rating"
]].head()

KeyError: "['is_paid', 'log_reviews', 'installs_per_rating'] not in index"

In [ ]:
#part7 reviews installs installs_per_rating

In [ ]:
!pip install scikit-learn

In [99]:
import numpy as np

df["installs_per_rating"] = df["installs"] / df["rating"]

In [100]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[[
    "reviews_norm",
    "installs_norm",
    "installs_per_rating_norm"
]] = scaler.fit_transform(
    df[[
        "reviews",
        "installs",
        "installs_per_rating"
    ]]
)

In [101]:
df[[
    "reviews", "reviews_norm",
    "installs", "installs_norm",
    "installs_per_rating", "installs_per_rating_norm"
]].head()

,reviews,reviews_norm,installs,installs_norm,installs_per_rating,installs_per_rating_norm
0,159,0.000002,10000,0.00001,2.439024e+03,0.000009
1,967,0.000012,500000,0.00050,1.282051e+05,0.000474
2,87510,0.001120,5000000,0.00500,1.063830e+06,0.003936
3,215644,0.002759,50000000,0.05000,1.111111e+07,0.041111
4,967,0.000012,100000,0.00010,2.325581e+04,0.000086

In [102]:
df.columns

Index(['app', 'category', 'rating', 'reviews', 'installs', 'type', 'price',
       'content_rating', 'genres', 'last_updated', 'current_ver',
       'android_ver', 'size_mb', 'installs_per_rating', 'reviews_norm',
       'installs_norm', 'installs_per_rating_norm'],
      dtype='str')

In [103]:
df["installs_per_rating"] = df["installs"] / df["rating"]

In [104]:
df[[
    "reviews", "reviews_norm",
    "installs", "installs_norm",
    "installs_per_rating", "installs_per_rating_norm"
]].head()

,reviews,reviews_norm,installs,installs_norm,installs_per_rating,installs_per_rating_norm
0,159,0.000002,10000,0.00001,2.439024e+03,0.000009
1,967,0.000012,500000,0.00050,1.282051e+05,0.000474
2,87510,0.001120,5000000,0.00500,1.063830e+06,0.003936
3,215644,0.002759,50000000,0.05000,1.111111e+07,0.041111
4,967,0.000012,100000,0.00010,2.325581e+04,0.000086

In [105]:
#part8

In [106]:
rating_anomalies = df[(df["rating"] < 0) | (df["rating"] > 5)]
rating_anomalies

Empty DataFrame
Columns: [app, category, rating, reviews, installs, type, price, content_rating, genres, last_updated, current_ver, android_ver, size_mb, installs_per_rating, reviews_norm, installs_norm, installs_per_rating_norm]
Index: []

In [107]:
Q1 = df["reviews"].quantile(0.25)
Q3 = df["reviews"].quantile(0.75)
IQR = Q3 - Q1

reviews_anomalies = df[
    (df["reviews"] < Q1 - 1.5 * IQR) |
    (df["reviews"] > Q3 + 1.5 * IQR)
]

reviews_anomalies.head()

,app,category,rating,reviews,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver,size_mb,installs_per_rating,reviews_norm,installs_norm,installs_per_rating_norm
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7,1.063830e+06,0.001120,0.005,0.003936
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25.0,1.111111e+07,0.002759,0.050,0.041111
18,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216,5000000,Free,0.0,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up,39.0,1.162791e+06,0.002485,0.005,0.004302
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,10000000,Free,0.0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up,31.0,2.173913e+06,0.002871,0.010,0.008043
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,10000000,Free,0.0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device,NaN,2.272727e+06,0.003777,0.010,0.008409

In [108]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

price_anomalies = df[
    (df["price"] < Q1 - 1.5 * IQR) |
    (df["price"] > Q3 + 1.5 * IQR)
]

price_anomalies.head()

,app,category,rating,reviews,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver,size_mb,installs_per_rating,reviews_norm,installs_norm,installs_per_rating_norm
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,100000,Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up,6.8,21276.595745,1.463952e-04,0.000100,0.000079
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,100000,Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up,39.0,20833.333333,1.317198e-04,0.000100,0.000077
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,100000,Paid,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up,NaN,25000.000000,2.334621e-04,0.000100,0.000092
476,"Moco+ - Chat, Meet People",DATING,4.2,1545,10000,Paid,3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up,NaN,2380.952381,1.976757e-05,0.000010,0.000009
477,Calculator,DATING,2.6,57,1000,Paid,6.99,Everyone,Dating,"October 25, 2017",1.1.6,4.0 and up,6.2,384.615385,7.292891e-07,0.000001,0.000001